"""initial migration with idempotency key

Revision ID: 0ef0ef992216
Revises: 
Create Date: 2026-02-19 10:30:22.076074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.database.session


# revision identifiers, used by Alembic.
revision: str = '0ef0ef992216'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('plan_tier', sa.Enum('STARTER', 'PRO', name='plantier'), nullable=False),
    sa.Column('subscription_status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELED', 'TRIAL', name='subscriptionstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login_ip', sa.String(), nullable=True),
    sa.Column('last_known_city', sa.String(), nullable=True),
    sa.Column('last_known_country', sa.String(), nullable=True),
    sa.Column('otp_code', sa.String(), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('assigned_phone_number', sa.String(), nullable=True),
    sa.Column('personal_whatsapp', sa.String(), nullable=True),
    sa.Column('openai_api_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_assigned_phone_number'), 'users', ['assigned_phone_number'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('business_profiles',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('user_id', src.database.session.GUID(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('ai_tone', sa.String(), nullable=True),
    sa.Column('products_services', sa.Text(), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('integrations',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('user_id', src.database.session.GUID(), nullable=False),
    sa.Column('platform_name', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('user_id', src.database.session.GUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('FACEBOOK', 'INSTAGRAM', 'WHATSAPP', 'MANUAL', 'LANDING_PAGE', name='leadsource'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'QUALIFIED', 'LOST', name='leadstatus'), nullable=False),
    sa.Column('transcription_summary', sa.Text(), nullable=True),
    sa.Column('original_transcript', sa.Text(), nullable=True),
    sa.Column('coach_feedback', sa.Text(), nullable=True),
    sa.Column('suggested_reply', sa.Text(), nullable=True),
    sa.Column('needs_followup', sa.Boolean(), nullable=True),
    sa.Column('followup_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_idempotency_key'), 'leads', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_user_id'), 'leads', ['user_id'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('owner_id', src.database.session.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_numbers_number'), 'phone_numbers', ['number'], unique=True)
    op.create_table('ai_agents',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('user_id', src.database.session.GUID(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('phone_number_id', src.database.session.GUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('coaching_sessions',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('user_id', src.database.session.GUID(), nullable=False),
    sa.Column('lead_id', src.database.session.GUID(), nullable=True),
    sa.Column('audio_file_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='sessionstatus'), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_interactions',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('user_id', src.database.session.GUID(), nullable=False),
    sa.Column('lead_id', src.database.session.GUID(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('media_type', sa.Enum('AUDIO', 'IMAGE', 'VIDEO', 'TEXT', name='mediatype'), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=True),
    sa.Column('transcription_text', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('suggested_reply', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_interactions_created_at'), 'media_interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_interactions_status'), 'media_interactions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_interactions_status'), table_name='media_interactions')
    op.drop_index(op.f('ix_media_interactions_created_at'), table_name='media_interactions')
    op.drop_table('media_interactions')
    op.drop_table('coaching_sessions')
    op.drop_table('ai_agents')
    op.drop_index(op.f('ix_phone_numbers_number'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index(op.f('ix_leads_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_idempotency_key'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('integrations')
    op.drop_table('business_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_assigned_phone_number'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
