"""feat(db): add WebhookDLQ for reliability and db indexes

Revision ID: a1d5a059d86f
Revises: d810f2836fe2
Create Date: 2026-03-09 00:27:20.760007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.database.session


# revision identifiers, used by Alembic.
revision: str = 'a1d5a059d86f'
down_revision: Union[str, Sequence[str], None] = 'd810f2836fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_dlq',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('provider', sa.Enum('TWILIO', 'VONAGE', 'META', 'CUSTOM', name='webhookprovider'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_dlq_created_at'), 'webhook_dlq', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_dlq_is_resolved'), 'webhook_dlq', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_webhook_dlq_provider'), 'webhook_dlq', ['provider'], unique=False)
    op.create_table('tags',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('user_id', src.database.session.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('lead_tag_association',
    sa.Column('lead_id', src.database.session.GUID(), nullable=False),
    sa.Column('tag_id', src.database.session.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lead_id', 'tag_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', src.database.session.GUID(), nullable=False),
    sa.Column('sender_type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_lead_id'), 'messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_coaching_sessions_created_at'), 'coaching_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_coaching_sessions_lead_id'), 'coaching_sessions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_coaching_sessions_status'), 'coaching_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_coaching_sessions_user_id'), 'coaching_sessions', ['user_id'], unique=False)
    op.drop_constraint(None, 'coaching_sessions', type_='foreignkey')
    op.drop_constraint(None, 'coaching_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'coaching_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'coaching_sessions', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_integrations_user_id'), 'integrations', ['user_id'], unique=False)
    op.add_column('leads', sa.Column('bot_active', sa.Boolean(), nullable=False))
    op.add_column('leads', sa.Column('requires_human', sa.Boolean(), nullable=False))
    op.add_column('leads', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('ai_rating', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('ai_feedback_note', sa.Text(), nullable=True))
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_followup_date'), 'leads', ['followup_date'], unique=False)
    op.create_index(op.f('ix_leads_needs_followup'), 'leads', ['needs_followup'], unique=False)
    op.create_index(op.f('ix_leads_phone_number'), 'leads', ['phone_number'], unique=False)
    op.create_index(op.f('ix_leads_requires_human'), 'leads', ['requires_human'], unique=False)
    op.create_index(op.f('ix_media_interactions_lead_id'), 'media_interactions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_media_interactions_user_id'), 'media_interactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_owner_id'), 'phone_numbers', ['owner_id'], unique=False)
    op.drop_constraint(None, 'phone_numbers', type_='foreignkey')
    op.create_foreign_key(None, 'phone_numbers', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_constraint(None, 'phone_numbers', type_='foreignkey')
    op.create_foreign_key(None, 'phone_numbers', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_phone_numbers_owner_id'), table_name='phone_numbers')
    op.drop_index(op.f('ix_media_interactions_user_id'), table_name='media_interactions')
    op.drop_index(op.f('ix_media_interactions_lead_id'), table_name='media_interactions')
    op.drop_index(op.f('ix_leads_requires_human'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone_number'), table_name='leads')
    op.drop_index(op.f('ix_leads_needs_followup'), table_name='leads')
    op.drop_index(op.f('ix_leads_followup_date'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_column('leads', 'ai_feedback_note')
    op.drop_column('leads', 'ai_rating')
    op.drop_column('leads', 'updated_at')
    op.drop_column('leads', 'requires_human')
    op.drop_column('leads', 'bot_active')
    op.drop_index(op.f('ix_integrations_user_id'), table_name='integrations')
    op.drop_constraint(None, 'coaching_sessions', type_='foreignkey')
    op.drop_constraint(None, 'coaching_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'coaching_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'coaching_sessions', 'leads', ['lead_id'], ['id'])
    op.drop_index(op.f('ix_coaching_sessions_user_id'), table_name='coaching_sessions')
    op.drop_index(op.f('ix_coaching_sessions_status'), table_name='coaching_sessions')
    op.drop_index(op.f('ix_coaching_sessions_lead_id'), table_name='coaching_sessions')
    op.drop_index(op.f('ix_coaching_sessions_created_at'), table_name='coaching_sessions')
    op.drop_index(op.f('ix_messages_lead_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('lead_tag_association')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_webhook_dlq_provider'), table_name='webhook_dlq')
    op.drop_index(op.f('ix_webhook_dlq_is_resolved'), table_name='webhook_dlq')
    op.drop_index(op.f('ix_webhook_dlq_created_at'), table_name='webhook_dlq')
    op.drop_table('webhook_dlq')
    # ### end Alembic commands ###
