"""add monthly ai messages counter to user

Revision ID: b2761dcfd8f7
Revises: 0ef0ef992216
Create Date: 2026-02-19 22:00:58.314664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.database.session


# revision identifiers, used by Alembic.
revision: str = 'b2761dcfd8f7'
down_revision: Union[str, Sequence[str], None] = '0ef0ef992216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('monthly_ai_messages', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'monthly_ai_messages')
    # ### end Alembic commands ###
