"""initial full database schema

Revision ID: bbaf27c9b091
Revises: 
Create Date: 2026-03-09 13:11:50.545084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.database.session


# revision identifiers, used by Alembic.
revision: str = 'bbaf27c9b091'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('plan_tier', sa.Enum('STARTER', 'PRO', name='plantier'), nullable=False),
    sa.Column('subscription_status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELED', 'TRIAL', name='subscriptionstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(), nullable=True),
    sa.Column('last_known_city', sa.String(), nullable=True),
    sa.Column('last_known_country', sa.String(), nullable=True),
    sa.Column('monthly_ai_messages', sa.Integer(), nullable=False),
    sa.Column('otp_code', sa.String(), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('assigned_phone_number', sa.String(), nullable=True),
    sa.Column('personal_whatsapp', sa.String(), nullable=True),
    sa.Column('openai_api_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_assigned_phone_number'), ['assigned_phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('webhook_dlq',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('provider', sa.Enum('TWILIO', 'VONAGE', 'META', 'CUSTOM', name='webhookprovider'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_dlq', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_dlq_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_dlq_is_resolved'), ['is_resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_dlq_provider'), ['provider'], unique=False)

    op.create_table('business_profiles',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('user_id', src.database.session.GUID(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('ai_tone', sa.String(), nullable=True),
    sa.Column('products_services', sa.Text(), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('integrations',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('user_id', src.database.session.GUID(), nullable=False),
    sa.Column('platform_name', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_user_id'), ['user_id'], unique=False)

    op.create_table('leads',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('user_id', src.database.session.GUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('FACEBOOK', 'FACEBOOK_AD', 'INSTAGRAM', 'WHATSAPP', 'GOOGLE_ADS', 'MANUAL', 'LANDING_PAGE', name='leadsource'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'QUALIFIED', 'LOST', name='leadstatus'), nullable=False),
    sa.Column('bot_active', sa.Boolean(), nullable=False),
    sa.Column('requires_human', sa.Boolean(), nullable=False),
    sa.Column('transcription_summary', sa.Text(), nullable=True),
    sa.Column('original_transcript', sa.Text(), nullable=True),
    sa.Column('coach_feedback', sa.Text(), nullable=True),
    sa.Column('suggested_reply', sa.Text(), nullable=True),
    sa.Column('needs_followup', sa.Boolean(), nullable=True),
    sa.Column('followup_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_rating', sa.Integer(), nullable=True),
    sa.Column('ai_feedback_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_followup_date'), ['followup_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_needs_followup'), ['needs_followup'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_requires_human'), ['requires_human'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_user_id'), ['user_id'], unique=False)

    op.create_table('phone_numbers',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('owner_id', src.database.session.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_numbers_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_phone_numbers_owner_id'), ['owner_id'], unique=False)

    op.create_table('tags',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('user_id', src.database.session.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_user_id'), ['user_id'], unique=False)

    op.create_table('ai_agents',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('user_id', src.database.session.GUID(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('phone_number_id', src.database.session.GUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('coaching_sessions',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('user_id', src.database.session.GUID(), nullable=False),
    sa.Column('lead_id', src.database.session.GUID(), nullable=True),
    sa.Column('audio_file_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='sessionstatus'), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coaching_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coaching_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_coaching_sessions_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coaching_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_coaching_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('lead_tag_association',
    sa.Column('lead_id', src.database.session.GUID(), nullable=False),
    sa.Column('tag_id', src.database.session.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lead_id', 'tag_id')
    )
    op.create_table('media_interactions',
    sa.Column('id', src.database.session.GUID(), nullable=False),
    sa.Column('user_id', src.database.session.GUID(), nullable=False),
    sa.Column('lead_id', src.database.session.GUID(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('media_type', sa.Enum('AUDIO', 'IMAGE', 'VIDEO', 'TEXT', name='mediatype'), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=True),
    sa.Column('transcription_text', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('suggested_reply', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_interactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_interactions_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_interactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_interactions_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', src.database.session.GUID(), nullable=False),
    sa.Column('sender_type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_lead_id'), ['lead_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_lead_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))

    op.drop_table('messages')
    with op.batch_alter_table('media_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_media_interactions_status'))
        batch_op.drop_index(batch_op.f('ix_media_interactions_lead_id'))
        batch_op.drop_index(batch_op.f('ix_media_interactions_created_at'))

    op.drop_table('media_interactions')
    op.drop_table('lead_tag_association')
    with op.batch_alter_table('coaching_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coaching_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_coaching_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_coaching_sessions_lead_id'))
        batch_op.drop_index(batch_op.f('ix_coaching_sessions_created_at'))

    op.drop_table('coaching_sessions')
    op.drop_table('ai_agents')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_user_id'))
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_numbers_owner_id'))
        batch_op.drop_index(batch_op.f('ix_phone_numbers_number'))

    op.drop_table('phone_numbers')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_user_id'))
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_requires_human'))
        batch_op.drop_index(batch_op.f('ix_leads_phone_number'))
        batch_op.drop_index(batch_op.f('ix_leads_needs_followup'))
        batch_op.drop_index(batch_op.f('ix_leads_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_leads_followup_date'))
        batch_op.drop_index(batch_op.f('ix_leads_email'))
        batch_op.drop_index(batch_op.f('ix_leads_created_at'))

    op.drop_table('leads')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_user_id'))

    op.drop_table('integrations')
    op.drop_table('business_profiles')
    with op.batch_alter_table('webhook_dlq', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_dlq_provider'))
        batch_op.drop_index(batch_op.f('ix_webhook_dlq_is_resolved'))
        batch_op.drop_index(batch_op.f('ix_webhook_dlq_created_at'))

    op.drop_table('webhook_dlq')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_index(batch_op.f('ix_users_assigned_phone_number'))

    op.drop_table('users')
    # ### end Alembic commands ###
