"""add monthly ai messages usage limit to users

Revision ID: d810f2836fe2
Revises: b2761dcfd8f7
Create Date: 2026-02-19 22:04:11.309279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.database.session


# revision identifiers, used by Alembic.
revision: str = 'd810f2836fe2'
down_revision: Union[str, Sequence[str], None] = 'b2761dcfd8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
