# src/services/communication/email.py
import os
import logging
from typing import List, Optional, Dict
from fastapi_mail import FastMail, MessageSchema, ConnectionConfig, MessageType
from pydantic import EmailStr
from src.config import settings

logger = logging.getLogger("EmailService")

class EmailService:
    """
    Asynchronous email service handler using fastapi-mail.
    Supports OTP delivery, PDFs, and now Admin Crash Alerts.
    """
    def __init__(self):
        self.conf = self._create_config()

    def _create_config(self) -> Optional[ConnectionConfig]:
        """
        Safely creates the connection configuration.
        Returns None if credentials are missing.
        """
        username = settings.MAIL_USERNAME
        password = settings.MAIL_PASSWORD
        
        if not username or not password:
            logger.warning("⚠️ SMTP Credentials missing in Config. Emails will NOT be sent (Log only).")
            return None

        try:
            return ConnectionConfig(
                MAIL_USERNAME=username,
                MAIL_PASSWORD=password,
                MAIL_FROM=settings.MAIL_FROM or "noreply@leadflow.ai",
                MAIL_PORT=int(settings.MAIL_PORT or 587),
                MAIL_SERVER=settings.MAIL_SERVER or "smtp-relay.brevo.com",
                MAIL_STARTTLS=True,
                MAIL_SSL_TLS=False,
                USE_CREDENTIALS=True,
                VALIDATE_CERTS=True
            )
        except Exception as e:
            logger.error(f"❌ Failed to configure SMTP: {e}")
            return None

    async def send_error_alert_email(self, error_summary: str, stack_trace: str, request_info: Dict):
        """
        NEW: Sends an emergency crash report to the System Administrator.
        """
        if not self.conf:
            logger.error(f"🛑 [MOCK CRASH ALERT] {error_summary}")
            return

        admin_email = getattr(settings, "ADMIN_EMAIL", None)
        if not admin_email:
            logger.warning("No ADMIN_EMAIL configured. Cannot send error alert.")
            return

        html_content = f"""
        <html>
          <body style="font-family: Arial, sans-serif; padding: 20px; color: #333; background-color: #fef2f2;">
            <div style="max-width: 800px; margin: auto; border: 1px solid #fca5a5; padding: 20px; border-radius: 10px; background-color: white;">
                <h2 style="color: #DC2626; border-bottom: 2px solid #fee2e2; padding-bottom: 10px;">🚨 Critical System Error</h2>
                <p><strong>Error Summary:</strong> <span style="color: #991B1B;">{error_summary}</span></p>
                
                <h3 style="color: #4B5563; margin-top: 20px;">Request Context:</h3>
                <table style="width: 100%; border-collapse: collapse; text-align: left; font-size: 14px;">
                    <tr style="background: #f3f4f6;">
                        <th style="padding: 8px; border: 1px solid #e5e7eb;">Method</th>
                        <td style="padding: 8px; border: 1px solid #e5e7eb;">{request_info.get('method', 'N/A')}</td>
                    </tr>
                    <tr>
                        <th style="padding: 8px; border: 1px solid #e5e7eb;">URL</th>
                        <td style="padding: 8px; border: 1px solid #e5e7eb;">{request_info.get('url', 'N/A')}</td>
                    </tr>
                    <tr style="background: #f3f4f6;">
                        <th style="padding: 8px; border: 1px solid #e5e7eb;">Client IP</th>
                        <td style="padding: 8px; border: 1px solid #e5e7eb;">{request_info.get('client_ip', 'N/A')}</td>
                    </tr>
                </table>

                <h3 style="color: #4B5563; margin-top: 20px;">Stack Trace:</h3>
                <pre style="background: #111827; color: #10B981; padding: 15px; border-radius: 8px; overflow-x: auto; font-size: 13px; line-height: 1.5;">{stack_trace}</pre>
                
                <p style="font-size: 12px; color: #6B7280; text-align: center; margin-top: 30px;">
                    Auto-generated by LeadFlow Exception Handler
                </p>
            </div>
          </body>
        </html>
        """

        try:
            message = MessageSchema(
                subject=f"🚨 LeadFlow Crash: {error_summary[:60]}",
                recipients=[admin_email],
                body=html_content,
                subtype=MessageType.html
            )

            fm = FastMail(self.conf)
            await fm.send_message(message)
            logger.info(f"✅ Crash report emailed to Admin ({admin_email})")

        except Exception as e:
            logger.error(f"❌ Failed to send crash email: {e}")

    async def send_otp_email(self, to_email: EmailStr, otp_code: str):
        if not self.conf:
            logger.info(f"🛑 [MOCK EMAIL] To: {to_email} | OTP: {otp_code}")
            return

        html_content = f"""
        <html>
          <body style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
            <div style="max-width: 500px; margin: auto; border: 1px solid #eee; padding: 20px; border-radius: 10px;">
                <h2 style="color: #4F46E5; text-align: center;">LeadFlow AI Security</h2>
                <p>Hello,</p>
                <p>Please use the following verification code to access your account:</p>
                <div style="text-align: center; margin: 30px 0;">
                    <span style="font-size: 32px; font-weight: bold; letter-spacing: 8px; background: #F3F4F6; padding: 15px 25px; border-radius: 8px; color: #111827;">
                        {otp_code}
                    </span>
                </div>
                <p>This code is valid for <b>5 minutes</b>.</p>
            </div>
          </body>
        </html>
        """

        try:
            message = MessageSchema(
                subject=f"Login Code: {otp_code}",
                recipients=[to_email],
                body=html_content,
                subtype=MessageType.html
            )
            fm = FastMail(self.conf)
            await fm.send_message(message)
        except Exception as e:
            logger.error(f"❌ Failed to send OTP email: {e}")

    async def send_payment_receipt(self, to_email: EmailStr, pdf_path: str):
        if not self.conf:
            logger.info(f"🛑 [MOCK RECEIPT] To: {to_email} | File: {pdf_path}")
            return
            
        if not os.path.exists(pdf_path):
            logger.error(f"❌ Attachment not found: {pdf_path}")
            return

        html_content = """
        <html>
          <body style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
            <div style="max-width: 600px; margin: auto; border: 1px solid #eee; padding: 30px; border-radius: 10px;">
                <h2 style="color: #4F46E5;">Welcome to MyLeads AI PRO! 🚀</h2>
                <p>Your payment was successful and your account has been instantly upgraded.</p>
                <p>You now have full access to our advanced AI Sales Agent features and unlimited lead processing.</p>
                <br>
                <p>Attached to this email is your official PDF tax invoice for your accounting records.</p>
                <br>
                <p>If you have any questions, simply reply to this email.</p>
                <p>Best regards,<br><b>The MyLeads AI Team</b></p>
            </div>
          </body>
        </html>
        """

        try:
            message = MessageSchema(
                subject="Your MyLeads AI Invoice & Account Upgrade",
                recipients=[to_email],
                body=html_content,
                subtype=MessageType.html,
                attachments=[pdf_path]
            )
            fm = FastMail(self.conf)
            await fm.send_message(message)
        except Exception as e:
            logger.error(f"❌ Failed to send invoice email: {e}")

# Singleton Instance
email_service = EmailService()

async def send_otp_email(to_email: str, otp_code: str):
    await email_service.send_otp_email(to_email, otp_code)